apiVersion: v1
kind: Pod
metadata:
  name: pod-emptydir
spec:
  containers:
    - name: cont-emptydir
      image: httpd
      volumeMounts:
        - mountPath: /cache
  volumes:
    - name: vol-emptydir
      emptyDir: {}
            