apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath
spec:
  containers:
    - name: cont-hostpath
      image: tomcat
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: vol-hostpath
          mountPath: /opt/
      resources:
        requests:
           memory: "64Mi"
           cpu: "128m"
        limits:
          memory: "128Mi"
          cpu: "256m"        
  volumes:
    - name: vol-hostpath
      hostPath:
        path: /opt/cont_hostPath_data/
