apiVersion: v1
kind: PersitentVolume
metadata:
  name: nfs-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
#A volume reclaim policy of retain indicates to preserve the volume after the pods.
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs-share
    server: 172.31.21.135
    readOnly: false

  
