---
# tasks file for tskgit.httpd
- name: Installing Apache on RHEL
  yum:
   name: "{{web_package_rhel}}"
   state: present
  when: ansible_os_family == "RedHat"
- name: Installing Apache on Debian
  apt:
#   update_cache: yes
   name: "{{web_package_deb}}"
   state: present
  when: ansible_os_family == "Debian"
- name: Updating index.html page
  template:
   src: index.html.j2
   dest: /var/www/html/index.html
  notify: Restarting the Web Service
- name: Settingup FACTS to web service
  set_fact:
   web_package: httpd
  when: ansible_os_family == "RedHat"
- name: Setting FACTS to Web Service when OS is Deb
  set_fact:
   web_package: apache2
  when: ansible_os_family == "Debian" 
   
    
