apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-configmap
data:
  index.html: |
    <!doctype html>
    <html>
      <head>
        <title>This is the title of the webpage!</title>
      </head>
      <body>
       <p>This is an example paragraph. Anything in the <strong>body</strong> tag will appear on the page, just like this <strong>p</strong> tag and its contents.</p>
      </body>
    </html>
  index2.html: |
    <html>
     <head>
      <title>Welcome To Kartheek's Tech World</title>
     </head>
    </html>

