apiVersion: v1
kind: Pod
metadata:
 name: mysql-pod
spec:
 containers:
  - image: mysql:5.7
    name: db-cont
    ports:
     - containerPort: 3306
    env:
     - name: MYSQL_ROOT_PASSWORD
       valueFrom:
        secretKeyRef:
         name: mysql-sec
         key: password
     - name: MYSQL_USER
       valueFrom:
        secretKeyRef:
         name: mysql-sec
         key: user
