#Generate Password and User Name in Encrypted format using below commands
#echo -n "root" | base64
#echo -n "welcome@1234" | base64
apiVersion: v1
kind: Secret
metadata:
 name: mysql-sec
type: Opaque
data:
 password: d2VsY29tZUAxMjM0
 user: cm9vdA==
